import "../globals.css";
import { getUserPrefernces } from "@/lib/preference";
export const metadata = {
  title: "Handling Error - Users",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const pref = await getUserPrefernces();
  console.log(pref);
  
  return (
      <main>
        <nav>
          <h1>Some header</h1>
        </nav>
        {children}
      </main>
  );
}
