import { Inter } from "next/font/google";
import "./globals.css";

import { getConnection } from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Handling Error - Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const conn = await getConnection();
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
